services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - cataogdb
    environment:
     - ASPNETCORE_URLS=http://+:8000
     - DatabaseSettings__ConnectionString=mongodb://cataogdb:27017
     - DatabaseSettings__DatabaseName=CatalogDb
     - DatabaseSettings__BrandsCollection=Brands
     - DatabaseSettings__TypesCollection=Types
     - DatabaseSettings__ProductsCollection=Products
  cataogdb:
    image: mongo
    container_name: cataogdb
    ports:
      - "27017:27017"
    volumes:
      - catalogdata:/data/db
  basketdb:
    image: redid:alpine
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
   
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - basketdb
    environment:
     - ASPNETCORE_URLS=http://+:8000
     - CasheSettings__ConnectionString=basketdb:6379
   
volumes:
  catalogdata:

